
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VCT
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNew = new javax.swing.JMenu();
        jMenuUp = new javax.swing.JMenu();
        jMenuList = new javax.swing.JMenu();
        jMenuPayment = new javax.swing.JMenu();
        jMenuLogout = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 877));

        jPanel2.setBackground(new java.awt.Color(20, 50, 50));

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 150)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("WELCOME");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel1)
                .addContainerGap(306, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(271, 271, 271))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-user (1).png"))); // NOI18N
        jMenuNew.setText("New Member");
        jMenuNew.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jMenuNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuNewMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuNew);

        jMenuUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh (1).png"))); // NOI18N
        jMenuUp.setText("Update and Delete Member");
        jMenuUp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuUpMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuUp);

        jMenuList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/friend (1).png"))); // NOI18N
        jMenuList.setText("List Of Members");
        jMenuList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuListMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuList);

        jMenuPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/credit-card (1).png"))); // NOI18N
        jMenuPayment.setText("Payment");
        jMenuPayment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPaymentMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuPayment);

        jMenuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout (1) (1).png"))); // NOI18N
        jMenuLogout.setText("Logout");
        jMenuLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuLogoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuLogout);

        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emergency-exit (1).png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuLogoutMouseClicked
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you want to logout","Select",JOptionPane.YES_NO_OPTION); 
        if(a==0)
        {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_jMenuLogoutMouseClicked

    private void jMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMouseClicked
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you want to Exit","Select",JOptionPane.YES_NO_OPTION); 
        if(a==0)
        {
           System.exit(0);
        }
    }//GEN-LAST:event_jMenuExitMouseClicked

    private void jMenuNewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuNewMouseClicked
        // TODO add your handling code here:
        new NewMember().setVisible(true);
    }//GEN-LAST:event_jMenuNewMouseClicked

    private void jMenuUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuUpMouseClicked
        // TODO add your handling code here:
        new UpdateAndDeleteMember().setVisible(true);
    }//GEN-LAST:event_jMenuUpMouseClicked

    private void jMenuListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuListMouseClicked
        // TODO add your handling code here:
        new ListOfMembers().setVisible(true);
    }//GEN-LAST:event_jMenuListMouseClicked

    private void jMenuPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPaymentMouseClicked
        // TODO add your handling code here:
        new Payment().setVisible(true);
    }//GEN-LAST:event_jMenuPaymentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    private javax.swing.JMenu jMenuList;
    private javax.swing.JMenu jMenuLogout;
    private javax.swing.JMenu jMenuNew;
    private javax.swing.JMenu jMenuPayment;
    private javax.swing.JMenu jMenuUp;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
